# .github/workflows/fetch-flags.yml
name: Fetch language flags
on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # <-- needed so the action can commit files
    steps:
      - uses: actions/checkout@v4

      - name: Download SVG flags
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p assets/flags
          BASE="https://cdn.jsdelivr.net/npm/flag-icons/flags/4x3"
          declare -A MAP=(
            [en]=gb [bg]=bg [hr]=hr [cs]=cz [da]=dk [nl]=nl [et]=ee [fi]=fi
            [fr]=fr [de]=de [el]=gr [hu]=hu [ga]=ie [it]=it [lv]=lv [lt]=lt
            [mt]=mt [pl]=pl [pt]=pt [ro]=ro [sk]=sk [sl]=si [es]=es [sv]=se
            [tr]=tr [ru]=ru [uk]=ua [nb]=no [nn]=no
          )
          for lang in "${!MAP[@]}"; do
            code="${MAP[$lang]}"
            curl -fsSL "$BASE/${code}.svg" -o "assets/flags/${lang}.svg"
          done

      - name: Commit flags
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "Add/refresh language flags (SVG)"
            file_pattern: assets/flags/*.svg
