name: Icon check

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  check-icons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate flat icon report
        run: python scripts/resolve_icons.py

      - name: Check that icon files exist
        run: |
          python - <<'PY'
          from pathlib import Path
          import csv, sys
          icons_dir = Path("assets/icons")
          need = set()
          for p in ["data/sections.csv","data/categories.csv","data/subcategories.csv"]:
              with open(p, encoding="utf-8-sig", newline="") as f:
                  for r in csv.DictReader(f):
                      v = (r.get("icon") or "").strip()
                      if v:
                          need.add(v.split("/")[-1])
          missing = [n for n in sorted(need) if not (icons_dir/n).exists()]
          if missing:
              print("Missing icons:")
              for m in missing: print(m)
              sys.exit(1)
          print("All icons present.")
          PY

      - name: Upload icon report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: icon-resolved-flat
          path: data/icon_resolved_flat.csv
