name: Icon check

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  check-icons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # don't stop the job if the checker finds missing files
      - name: Run icon checker
        run: python scripts/check_icons.py
        continue-on-error: true

      # always try to auto-resolve
      - name: Resolve icons (create placeholders)
        if: always()
        run: python scripts/resolve_icons.py

      - name: Commit placeholders
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: add placeholder icons'
          file_pattern: assets/icons/*.svg

      - name: Upload icon report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: icon-report
          path: data/icon_report.csv
