name: Icon check (manual)

on:
  workflow_dispatch: {}   # run only when triggered from the Actions tab

permissions:
  contents: read

jobs:
  icon-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Optional deps if you keep a requirements.txt
      - name: Install dependencies
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      # Try to generate the flat icon report, but never fail the job
      - name: Generate flat icon report (non-blocking)
        run: python scripts/resolve_icons.py || true

      # Make sure there is always an artifact to upload
      - name: Ensure report file exists
        run: |
          mkdir -p data
          [ -f data/icon_resolved_flat.csv ] || echo "level,id,parent_id,label,resolved_icon,source" > data/icon_resolved_flat.csv

      - name: Upload icon report
        uses: actions/upload-artifact@v4
        with:
          name: icon-report
          path: data/icon_resolved_flat.csv
