name: Icon check

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  check-icons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run icon checker
        run: python scripts/check_icons.py

      - name: Resolve icons (flat report)
        run: python scripts/resolve_icons.py

      - name: Upload icon report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: icon-report
          path: data/icon_report.csv

      - name: Upload resolved icons
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: icon-resolved-flat
          path: data/icon_resolved_flat.csv
